### ISSUE TITLE
xapian.InvalidArgumentError: Term too long while rebuilding index

### ISSUE THREAD

**Issue by gremmie** [notanumber/xapian-haystack#153]
While trying to rebuild the search index with Haystack v2.3.1 and a3a3a4e7cfba3e2e1be3a42abf59edd29ea03c05 of the xapian backend I got a traceback, see below. 

Curiously this didn't happen with Haystack 2.1.0 and 37add92 of the backend. It could be this is new data, I'm not really sure.

I'd be fine with just silently truncating the data if it is too long.

````
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 16, in handle
    call_command('update_index', **options)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 189, in handle_label
    self.update_backend(label, using)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 234, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/brian/coding/python/venvs/sg101/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 89, in do_update
    backend.update(index, current_qs)
  File "/home/brian/coding/python/venvs/sg101/src/xapian-haystack/xapian_backend.py", line 486, in update
    database.replace_document(document_id, document)
xapian.InvalidArgumentError: Term too long (> 245): XTEXT[http://www.elderly.com/books/cat_or_pgc_page?page=2&query_start=21&step=20&cat_or_pgc=650&special_links=&sort_on=cat_or_pgc,artist,title](http://www.elderly.com/books/cat_or_pgc_page?page=2&query_start=21&step=20&cat_or_pgc=650&special_links=&sort_on=cat_or_pgc%2cartist%2ctitle)
````

**Comment by gremmie** [comment]
It seems like this was discussed [in this djago-haystack google group thread](https://groups.google.com/d/topic/django-haystack/hRJKcPNPXqw/discussion).

**Comment by Henner** [comment]
but the solution there is wrong!
the word length is limited not the text itself

try something like:
https://stackoverflow.com/questions/30925487/xapian-search-terms-which-exceed-the-245-character-length-invalidargumenterror

or do it in a template filter
