### ISSUE TITLE
django-haystack 1.4

### ISSUE THREAD

**Issue by Reivax84** [notanumber/xapian-haystack#170]
hello,
is there a particular reason why commit d3f1e01 removed compatibility to django-haystack 1.4?

Greetings
Xavier

**Comment by alexsilva** [comment]
This commit broke compatibility with django-haystack == 2.5.1

**Comment by alexsilva** [comment]
Neither version django-haystack==2.6 work anymore. This commit needs to be rolled back.

**Comment by alexsilva** [comment]
The following error occurs at the time the `update_index` command is executed.
```
Traceback (most recent call last):
  File "manage.py", line 40, in <module>
    execute_from_command_line(sys.argv)
  File "\Python2.7\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "\Python2.7\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "\Python2.7\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "\Python2.7\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "\pyenv\Lib\site-packages\haystack\management\commands\update_index.py", line 214, in handle
    self.update_backend(label, using)
  File "\pyenv\Lib\site-packages\haystack\management\commands\update_index.py", line 257, in update_backend
    commit=self.commit, max_retries=self.max_retries)
  File "\pyenv\Lib\site-packages\haystack\management\commands\update_index.py", line 84, in do_update
    backend.update(index, current_qs, commit=commit)
TypeError: update() got an unexpected keyword argument 'commit'
```

**Comment by alexsilva** [comment]
[#171](https://github.com/notanumber/xapian-haystack/pull/171)

**Comment by claudep** [comment]
I guess this is now obsolete.
