### ISSUE TITLE
Multiprocess indexing, locking exceptions

### ISSUE THREAD

**Issue by karolyi** [notanumber/xapian-haystack#174]
Hey,

I just changed from Whoosh as I have a lot of data for which xapian seems to be better, by measuring the results.

My only problem so far is, I can't use `django-haystack`'s multiprocess indexing. When I specify the `-k` option for it to change into multiprocess mode to speed up indexing, I get a lot of tracebacks similar to this:

```python
  indexed 1001 - 2000 of 165017 (worker PID: 5456).
[WARNING/ForkPoolWorker-2] Failed indexing 21001 - 22000 (retry 2/5): Unable to get write lock on /project/backend/xapian_index/lang-de-de: already locked (pid 5457): Unable to get write lock on /project/backend/xapian_index/lang-de-de: already locked
Traceback (most recent call last):
  File "/project/venv/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 86, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/project/backend/ticketshop/base/haystack.py", line 67, in update
    multilingual=False)
  File "/project/backend/ticketshop/base/haystack.py", line 70, in update
    super().update(index=index, iterable=iterable, commit=commit)
  File "/project/venv/lib/python3.6/site-packages/xapian_backend.py", line 282, in update
    database = self._database(writable=True)
  File "/project/venv/lib/python3.6/site-packages/xapian_backend.py", line 1156, in _database
    database = xapian.WritableDatabase(self.path, xapian.DB_CREATE_OR_OPEN)
  File "/project/venv/lib/python3.6/site-packages/xapian/__init__.py", line 9175, in __init__
    _xapian.WritableDatabase_swiginit(self, _xapian.new_WritableDatabase(*args))xapian.DatabaseLockError: Unable to get write lock on /project/backend/xapian_index/lang-de-de: already locked
```

Any idea on how to fix this?

**Comment by karolyi** [comment]
Bump.

This is getting severe. It causes exceptions on multiprocessed django (production), because the lack of lock handling.

**Comment by karolyi** [comment]
bump

**Comment by karolyi** [comment]
Alright, here's my solution. I've also built a multilingual database, so it might be a bit convoluted, but you'll get the idea. Feel free to use in the project. It works with multiprocess indexing.
```python
from functools import lru_cache
from fcntl import flock, LOCK_EX, LOCK_UN

from django.conf import settings
from django.db.models.signals import post_delete, post_save
from django.utils.translation import activate, get_language
from haystack import connections
from haystack.backends import BaseEngine
from haystack.constants import DEFAULT_ALIAS
from haystack.exceptions import NotHandled
from haystack.signals import BaseSignalProcessor
from xapian_backend import XapianSearchBackend, XapianSearchQuery


@lru_cache(maxsize=5)
def get_using(language: str) -> str:
    new_using = 'lang-' + language
    using = new_using if new_using in settings.HAYSTACK_CONNECTIONS \
        else DEFAULT_ALIAS
    return using


class ContextLock(object):
    """
    A context-using file locker. HEADS UP: man 2 flock:

    Locks are on files, not file descriptors.  That is, file descriptors
    duplicated through dup(2) or fork(2) do not result in multiple
    instances of a lock, but rather multiple references to a single
    lock. If a process holding a lock on a file forks and the child
    explicitly unlocks the file, the parent will lose its lock.

    Processes blocked awaiting a lock may be awakened by signals.
    """

    def __init__(self, path: int):
        self.path = path

    def __enter__(self):
        """Enter the lock."""
        self.file = open(self.path, 'r')
        flock(self.file, LOCK_EX)

    def __exit__(self, exc_type, exc_value, traceback):
        """Exit the lock."""
        flock(self.file, LOCK_UN)
        self.file.close()


class TicketShopMultilingualXapianSearchBackend(XapianSearchBackend):
    """
    Xapian backend engine for multilanguage search, based on
    http://anthony-tresontani.github.io/Django/2012/09/20/multilingual-search/
    and adjusted for our needs.
    """

    def update(self, index, iterable, commit=True, multilingual=True):
        """
        Only update the backend with the assigned language.

        !!! IMPORTANT !!!
        When rebuilding/updating, specify only one language:
        backend/manage.py rebuild_index --noinput -v 2 -u lang-de-de

        The backend will update all used languages.
        """
        if multilingual:
            initial_language = get_language() or settings.LANGUAGE_CODE
            for lang, lang_str in settings.LANGUAGES:
                using = get_using(language=lang)
                backend_language = settings.HAYSTACK_CONNECTIONS[using].get(
                    'ticketshop-lang', settings.LANGUAGE_CODE)
                activate(language=backend_language)
                backend = connections[using].get_backend()
                backend.ts_settings = settings.HAYSTACK_CONNECTIONS[using]
                backend.update(
                    index=index, iterable=iterable, commit=commit,
                    multilingual=False)
                activate(language=initial_language)
            return
        with ContextLock(path=self.ts_settings['ticketshop-lockfile']):
            super().update(index=index, iterable=iterable, commit=commit)

    def remove(self, obj, commit=True, is_multilingual: bool=True):
        """
        Remove indexes for `obj` from the database.

        We delete all instances of `Q<app_name>.<model_name>.<pk>` which
        should be unique to this object.

        Optional arguments:
           `commit` -- ignored
        """
        if is_multilingual:
            for lang, lang_str in settings.LANGUAGES:
                using = get_using(language=lang)
                backend = connections[using].get_backend()
                backend.ts_settings = settings.HAYSTACK_CONNECTIONS[using]
                backend.remove(obj=obj, commit=commit, is_multilingual=False)
            return
        with ContextLock(path=self.ts_settings['ticketshop-lockfile']):
            return super().remove(obj=obj, commit=commit)


class TicketShopMultilingualXapianSearchQuery(XapianSearchQuery):
    """Searching always in the current language."""

    def __init__(self, using=DEFAULT_ALIAS):
        language = get_language() or settings.LANGUAGE_CODE
        using = get_using(language=language)
        super().__init__(using=using)


class TicketShopSearchEngine(BaseEngine):
    """Implementing a multilingual search backend."""
    backend = TicketShopMultilingualXapianSearchBackend
    query = TicketShopMultilingualXapianSearchQuery
```
